[33mproxy: initializing cSide...[0m
[32mclientSide: __init__ called[0m
[32mclientSide: socket created[0m
[32mclientSide: socket bound[0m
[32mclientSide: socket listening[0m
[33mproxy: cSide initialized[0m
[33mproxy: initializing sSide...[0m
[36mserverSide: __init__ called[0m
[36mserverSide: socket created[0m
[36mserverSide: socket bound[0m
[33mproxy: sSide initiaized[0m
[33mproxy: Ip address of the proxy is: 192.168.254.74[0m
[33mproxy: started cSide[0m
[32mclientSide: run called[0m
[36mserverSide: run called[0m
[33mproxy: started sSide[0m
[32mclientSide: Waiting for client connection...[0m
[36mserverSide: waiting for client to get connection...  [0m
[32mclientSide: Waiting for client connection...[0m
[32mclientSide: Waiting for client connection...[0m
[32mclientSide: Waiting for client connection...[0m
command invoked: stop
[33mproxy: Stopping...[0m
[32mclientSide: Stopping...[0m
[32mclientSide: Cannot close socket.[0m
[32mclientSide: Closed client connection.[0m
[36mserverSide: Stopping...[0m
[36mserverSide: Disconnected from server.[0m
[33mproxy: Joining cSide thread...[0m
[32mclientSide: Waiting for client connection...[0m
[32mclientSide: loop broken[0m
[31mcleanup: Exception in <clientSide(Thread-1, started 2496)>. Printing traceback:
NoneType: None
[0m
[31mcleanup: Cleaning up after exception in <clientSide(Thread-1, started 2496)>.[0m
[33mproxy: Stopping...[0m
[32mclientSide: Stopping...[0m
[32mclientSide: Cannot close socket.[0m
[32mclientSide: Closed client connection.[0m
[36mserverSide: Stopping...[0m
[36mserverSide: Disconnected from server.[0m
[33mproxy: Joining cSide thread...[0m
[31mcleanup: Exception in <TCP.proxy object at 0x0000014A5DFFD788>. Printing traceback:
Traceback (most recent call last):
  File "C:\Users\aweso\Documents\Source\Python\proxy\TCP.py", line 69, in stop
    self.cSide.join()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 1041, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
[0m
[31mcleanup: Cleaning up after exception in <TCP.proxy object at 0x0000014A5DFFD788>.[0m
[33mproxy: Could not join cSide thread.[0m
[33mproxy: cSide thread joined.[0m
[31mcleanup: Exception in <TCP.proxy object at 0x0000014A5DFFD788>. Printing traceback:
NoneType: None
[0m
[31mcleanup: Cleaning up after exception in <TCP.proxy object at 0x0000014A5DFFD788>.[0m
[33mproxy: Could not join cSide thread.[0m
[33mproxy: Joining sSide thread...[0m
